test('Test', () => {});

test('Error', () => {
  throw new Error('Failure!');
});
